routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    App\Http\Controllers\HomeController::class,
    'index'
])->name('home');

Auth::routes([ 'verify' => true ]);

Route::group([
    'middleware' => [
        'auth',
        'verified'
    ]
], function () {

    Route::resource('communities', App\Http\Controllers\CommunityController::class);

    Route::resource('communities.posts', App\Http\Controllers\PostController::class);

    Route::resource('posts.comments', App\Http\Controllers\CommentController::class);

    Route::get('posts/{post_id}/vote/{vote}', [
        App\Http\Controllers\PostVoteController::class,
        'store'
    ])->name('posts.vote');

    Route::post('posts/{post_id}/report', [
        App\Http\Controllers\PostVoteController::class,
        'report'
    ])->name('posts.report');

});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model {

    use HasFactory, SoftDeletes;

    protected $fillable = [
        'title',
        'post_text',
        'post_image',
        'post_url',
        'user_id',
        'votes',
        'community_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function community(): BelongsTo
    {
        return $this->belongsTo(Community::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class)->latest();
    }

    public function votesThisWeek()
    {
        return $this->hasMany(PostVote::class)
            ->where('post_votes.created_at', '>=', now()->subDays(7));
    }

    public function postVotes()
    {
        return $this->hasMany(PostVote::class);
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Community;
use App\Models\Post;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use Illuminate\Support\Facades\Gate;

class PostController extends Controller {

    public function index(Community $community)
    {
        $posts = $community->posts()->latest('id')->paginate(10);
    }


    public function create(Community $community)
    {
        return view('posts.create', [
            'community' => $community,
        ]);
    }

    public function store(StorePostRequest $request, Community $community)
    {

        $post = $community->posts()->create([
            'user_id'   => auth()->id(),
            'title'     => $request->title,
            'post_url'  => $request->post_url ?? '',
            'post_text' => $request->post_text ?? '',
        ]);

        if ( $request->hasFile('post_image') ) {
            $image = $request->file('post_image')->getClientOriginalName();
            $request->file('post_image')
                ->storeAs('posts/' . $post->id, $image);
            $post->update([ 'post_image' => $image ]);
        }


        return redirect()->route('communities.show', $community);
    }

    public function show(Community $community, Post $post)
    {
        $post->load('comments.user');

        return view('posts.show', [
            'community' => $community,
            'post'      => $post,
        ]);
    }

    public function edit(Community $community, Post $post)
    {
        if ( Gate::denies('edit-post', $post) ) {
            abort(403);
        }

        return view('posts.edit', [
            'community' => $community,
            'post'      => $post,
        ]);
    }

    public function update(UpdatePostRequest $request, Community $community, Post $post)
    {
        if ( Gate::denies('edit-post', $post) ) {
            abort(403);
        }

        $post->update([
            'title'     => $request->title,
            'post_url'  => $request->post_url ?? '',
            'post_text' => $request->post_text ?? '',
        ]);

//        $post->update($request->validated());

        if ( $request->hasFile('post_image') ) {
            $image = $request->file('post_image')->getClientOriginalName();
            $request->file('post_image')
                ->storeAs('posts/' . $post->id, $image);

            if ( $post->post_image != '' ) {
                unlink(storage_path('app/public/posts/' . $post->id . '/' . $post->post_image));
            }

            $post->update([ 'post_image' => $image ]);
        }


        return redirect()->route('communities.posts.show', [
            $community,
            $post
        ]);
    }

    public function destroy(Community $community, Post $post)
    {
        if ( Gate::denies('delete-post', $post) ) {
            abort(403);
        }

        $post->delete();

        return redirect()->route('communities.show', $community);
    }

}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            {{ $community->name }}: Add Post
        </div>
        
        <div class="card-body">
            
            <form method="POST"
                  enctype="multipart/form-data"
                  action="{{ route('communities.posts.store', $community) }}">
                @csrf
                <div class="row mb-3">
                    <label for="title"
                           class="col-md-4 col-form-label text-md-end">
                        {{ __('Title') }}*
                    </label>
                    
                    <div class="col-md-6">
                        <input id="title" type="text" class="form-control
                                @error('title') is-invalid @enderror" name="title"
                               value="{{ old('title') }}"
                               autofocus>
                        
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                <div class="row mb-3">
                    <label for="post_text" class="col-md-4 col-form-label text-md-end">
                        {{ __('Post Text') }}
                    </label>
                    
                    <div class="col-md-6">
                                    <textarea rows="10" class="form-control @error('post_text')
                                    is-invalid
                                     @enderror" name="post_text">{{ old('post_text') }}</textarea>
                        @error('post_text')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                <div class="row mb-3">
                    <label for="post_url"
                           class="col-md-4 col-form-label text-md-end">
                        {{ __('URL Link') }}
                    </label>
                    
                    <div class="col-md-6">
                        <input id="post_url" type="text" class="form-control
                                @error('post_url') is-invalid @enderror" name="post_url"
                               value="{{ old('post_url') }}"
                               autofocus>
                        
                        @error('post_url')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                <div class="row mb-3">
                    <label for="post_image"
                           class="col-md-4 col-form-label text-md-end">
                        {{ __('Image') }}
                    </label>
                    
                    <div class="col-md-6">
                        <input type="file" name="post_image" class="form-control
                                @error('post_image') is-invalid @enderror">
                        
                        @error('post_image')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                
                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Create Post') }}
                        </button>
                    </div>
                </div>
            </form>
        
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            In {{ $community->name }}: Edit Post
        </div>
        
        <div class="card-body">
            
            <form method="POST"
                  enctype="multipart/form-data"
                  action="{{ route('communities.posts.update', [$community, $post]) }}">
                @csrf
                @method('PUT')
                
                <div class="row mb-3">
                    <label for="title"
                           class="col-md-4 col-form-label text-md-end">
                        {{ __('Title') }}*
                    </label>
                    
                    <div class="col-md-6">
                        <input id="title" type="text" class="form-control
                                @error('title') is-invalid @enderror" name="title"
                               value="{{ $post->title }}" required
                               autofocus>
                        
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                <div class="row mb-3">
                    <label for="post_text" class="col-md-4 col-form-label text-md-end">
                        {{ __('Post Text') }}
                    </label>
                    
                    <div class="col-md-6">
                                    <textarea rows="10" class="form-control @error('post_text')
                                    is-invalid
                                     @enderror" name="post_text">{{ $post->post_text }}</textarea>
                        @error('post_text')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                <div class="row mb-3">
                    <label for="post_url"
                           class="col-md-4 col-form-label text-md-end">
                        {{ __('URL Link') }}
                    </label>
                    
                    <div class="col-md-6">
                        <input id="post_url" type="url" class="form-control
                                @error('post_url') is-invalid @enderror" name="post_url"
                               value="{{ $post->post_url }}"
                               autofocus>
                        
                        @error('post_url')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                
                @if ($post->post_image)
                    <div class="row mb-3">
                        <label for="post_image"
                               class="col-md-4 col-form-label text-md-end">
                            {{ __('Post Image') }}
                        </label>
                        
                        <div class="col-md-6">
                            <img src="{{ asset('storage/posts/' . $post->id . '/' . $post->post_image ) }}"
                                 class="img-thumbnail"
                                 alt="{{ $post->title }}">
                        </div>
                    </div>
                @endif
                
                
                <div class="row mb-3">
                    <label for="post_image"
                           class="col-md-4 col-form-label text-md-end">
                        {{ __('Image') }}
                    </label>
                    
                    <div class="col-md-6">
                        <input type="file" name="post_image" class="form-control
                                @error('post_image') is-invalid @enderror">
                        
                        @error('post_image')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                
                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Save') }}
                        </button>
                        <a href="{{ route('communities.posts.show', [$community, $post])
                                     }}"
                           class="btn btn-secondary">
                            {{ __('Cancel') }}
                        </a>
                    </div>
                </div>
            </form>
        
        </div>
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    @if(session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    <div class="card">
        <div class="card-header">
            {{ $post->title }}
            <div class="float-sm-end">
                <p class="" style="display: inline;">
                    Vote : {{ $post->votes }}
                </p>
                @can('delete-post', $post)
                |
                @else
                    <form method="POST"
                          onclick="return confirm('Are you sure you want to report this post?')"
                          style="display: inline-block"
                          action="{{ route('posts.report', $post->id) }}">
                        @csrf
                        <button
                                type="submit"
                                class="btn btn-sm btn-link">Report this post
                        </button>
                    </form>
                @endcan
            </div>
        </div>
        
        <div class="card-body">
            
            @if($post->post_url)
                <div class="row mb-2">
                    <div class="col-md-12">
                        <a href="{{ $post->post_url }}"
                           target="_blank">{{ $post->post_url }}</a>
                    </div>
                </div>
            @endif
            @if($post->post_image)
                <div class="row">
                    <div class="col-md-12">
                        <img src="{{ asset('storage/posts/' . $post->id . '/' . $post->post_image ) }}"
                             class="img-fluid"
                             alt="{{ $post->title }}">
                    </div>
                </div>
            @endif
            <div class="row mt-1">
                <div class="col-md-12">
                    <p>{{ $post->post_text }}</p>
                </div>
            </div>
            
        </div>
        
        <div class="card-footer">
            <div class="row">
                <div class="col-md-6">
                    <a href="{{ route('communities.show', [$community]) }}"
                       class="btn btn-sm btn-secondary">
                        {{ __('Back to Community') }}
                    </a>
                    @auth
                        @can('edit-post', $post)
                            <a href="{{ route('communities.posts.edit', [$community, $post])
                             }}"
                               class="btn btn-sm
                                btn-primary">Edit</a>
                        @endcan
                        @can('delete-post', $post)
                            
                            <form method="POST"
                                  style="display: inline-block"
                                  action="{{ route('communities.posts.destroy', [$community,
                                  $post]) }}">
                                @csrf
                                @method('DELETE')
                                <button onclick="return confirm('Are you sure?')"
                                        type="submit"
                                        class="btn btn-sm btn-danger">Delete
                                </button>
                            </form>
                        @endcan
                    @endauth
                </div>
            </div>
        
        
        </div>
    </div>

@endsection

@section('some-content')
    
    @include('comments.index', ['post' => $post])
@endsection