routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    App\Http\Controllers\HomeController::class,
    'index'
])->name('home');

Auth::routes([ 'verify' => true ]);

Route::group([
    'middleware' => [
        'auth',
        'verified'
    ]
], function () {

    Route::resource('communities', App\Http\Controllers\CommunityController::class);

    Route::resource('communities.posts', App\Http\Controllers\PostController::class);

    Route::resource('posts.comments', App\Http\Controllers\CommentController::class);

    Route::get('posts/{post_id}/vote/{vote}', [
        App\Http\Controllers\PostVoteController::class,
        'store'
    ])->name('posts.vote');

    Route::post('posts/{post_id}/report', [
        App\Http\Controllers\PostVoteController::class,
        'report'
    ])->name('posts.report');

});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'post_id',
        'comment_text',
    ];


    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Http\Requests\StoreCommentRequest;
use App\Http\Requests\UpdateCommentRequest;
use App\Models\Post;

class CommentController extends Controller {

    public function store(StoreCommentRequest $request, Post $post)
    {
        $post->load('community');

        $post->comments()->create($request->validated() + [
                'user_id' => auth()->id(),
            ]);

        return redirect()->route('communities.posts.show', [
            $post->community,
            $post,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\UpdateCommentRequest $request
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCommentRequest $request, Comment $comment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        //
    }

}

resources/views/comments/index.blade.php
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Comments for {{ $post->title }}
                </div>
                <div class="card-body">
                    
                    <div class="row">
                        <div class="col-md-12">
    
                            <form method="POST" action="{{ route('posts.comments.store', $post)
                            }}">
        
                                @csrf
                                <div class="form-group">
                                    <label for="comment_text">Comment</label>
                                    <textarea
                                            class="form-control @error('comment_text') is-invalid @enderror"
                                            id="comment_text" name="comment_text"
                                            rows="3"></textarea>
                                </div>
        
                                <div class="form-group">
                                    <button type="submit"
                                            class="mt-3 mb-2 btn btn-sm btn-secondary float-sm-end">
                                        {{ __('Add Comment') }}
                                    </button>
                                </div>
    
                            </form>
                        </div>
                    </div>
                    
                    <div class="mt-3">
                        @forelse($post->comments as $comment)
                            <div class="card mt-3">
                                <div class="card-body">
                                    <p>{{ $comment->comment_text }}</p>
                                    <div class="row">
                                        <div class="col-md-12 text-muted">
                                            <small>
                                                {{ $comment->user->name }}
                                                {{ $comment->created_at->diffForHumans() }}
                                            </small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @empty
                            <p>No comments yet.</p>
                        @endforelse
                    </div>
                </div>
                <div class="card-footer">
                    Something here
                </div>
            </div>
        </div>
    </div>
</div>