routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    App\Http\Controllers\HomeController::class,
    'index'
])->name('home');

Auth::routes([ 'verify' => true ]);

Route::group([
    'middleware' => [
        'auth',
        'verified'
    ]
], function () {

    Route::resource('communities', App\Http\Controllers\CommunityController::class);

    Route::resource('communities.posts', App\Http\Controllers\PostController::class);

    Route::resource('posts.comments', App\Http\Controllers\CommentController::class);

    Route::get('posts/{post_id}/vote/{vote}', [
        App\Http\Controllers\PostVoteController::class,
        'store'
    ])->name('posts.vote');

    Route::post('posts/{post_id}/report', [
        App\Http\Controllers\PostVoteController::class,
        'report'
    ])->name('posts.report');

});

app/Models/Community.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Community extends Model
{
    use HasFactory, SoftDeletes, Sluggable;

    protected $fillable = [
        'name',
        'slug',
        'description',
        'user_id',
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function topics()
    {
        return $this->belongsToMany(Topic::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CommunityController.php
<?php

namespace App\Http\Controllers;

use App\Models\Community;
use App\Http\Requests\StoreCommunityRequest;
use App\Http\Requests\UpdateCommunityRequest;
use App\Models\Post;
use App\Models\Topic;
use Illuminate\Support\Str;

class CommunityController extends Controller {

    public function index()
    {
        $communities = Community::where('user_id', auth()->id())->get();

        return view('communities.index', [
            'communities' => $communities,
        ]);
    }


    public function create()
    {
        $topics = Topic::all();

        return view('communities.create', [
            'topics' => $topics,
        ]);
    }

    public function store(StoreCommunityRequest $request)
    {
        $community = Community::create($request->validated() + [
                'user_id' => auth()->id(),
            ]);
        $community->topics()->attach($request->topics);

        return redirect()->route('communities.show', $community);
    }

    public function show(Community $community)
    {
        $query = $community->posts();

        if (request('sort', '') === 'popular') {
            $query->orderBy('votes', 'desc');
        } else {
            $query->latest('id');
        }

        $posts = $query->paginate(5);

        return view('communities.show', [
            'community' => $community,
            'posts'     => $posts,
        ]);
    }


    public function edit(Community $community)
    {

        if ( $community->user_id !== auth()->id() ) {
            abort(403);
        }

        $community->load('topics');

        return view('communities.edit', [
            'community' => $community,
            'topics'    => Topic::all(),
        ]);
    }


    public function update(UpdateCommunityRequest $request, Community $community)
    {
        if ( $community->user_id !== auth()->id() ) {
            abort(403);
        }

        $community->update($request->validated());
        $community->topics()->sync($request->topics);

        return redirect()->route('communities.index')->with('message', 'Community updated successfully.');
    }

    public function destroy(Community $community)
    {
        if ( $community->user_id !== auth()->id() ) {
            abort(403);
        }

        $community->delete();

        return redirect()->route('communities.index')->with('message', 'Community deleted');
    }

}

resources/views/communities/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">{{ __('New Community') }}</div>
        
        <div class="card-body">
            <form method="POST" action="{{ route('communities.store') }}">
                @csrf
                
                <div class="row mb-3">
                    <label for="name"
                           class="col-md-4 col-form-label text-md-end">{{ __('Name')
                                       }}*</label>
                    
                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control
                                @error('name') is-invalid @enderror" name="name"
                               value="{{ old('name') }}" required autocomplete="name"
                               autofocus>
                        
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                <div class="row mb-3">
                    <label for="email" class="col-md-4 col-form-label text-md-end">{{ __
                            ('Description') }}*</label>
                    
                    <div class="col-md-6">
                        <textarea class="form-control @error('description') is-invalid @enderror"
                                  name="description"></textarea>
                        @error('description')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                
                <div class="row mb-3">
                    <label for="topics" class="col-md-4 col-form-label text-md-end">{{ __
                            ('Topics') }}</label>
                    
                    <div class="col-md-6">
                        <select name="topics[]" multiple class="form-control select2">
                            @foreach ($topics as $topic)
                                <option value="{{ $topic->id }}">{{ $topic->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                
                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Create Community') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/communities/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit Community') }}</div>
                    
                    <div class="card-body">
                        <form method="POST" action="{{ route('communities.update', $community) }}">
                            @csrf
                            @method('PUT')
                            <div class="row mb-3">
                                <label for="name"
                                       class="col-md-4 col-form-label text-md-end">{{ __('Name')
                                       }}*</label>
                                
                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control
                                @error('name') is-invalid @enderror" name="name"
                                           value="{{ $community->name }}" required
                                           autocomplete="name"
                                           autofocus>
                                    
                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="row mb-3">
                                <label for="email" class="col-md-4 col-form-label text-md-end">{{ __
                            ('Description') }}*</label>
                                
                                <div class="col-md-6">
                                    <textarea
                                            class="form-control @error('description') is-invalid @enderror"
                                            name="description">{{ $community->description }}</textarea>
                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="row mb-3">
                                <label for="topics" class="col-md-4 col-form-label text-md-end">{{ __
                            ('Topics') }}</label>
                                
                                <div class="col-md-6">
                                    <select name="topics[]" multiple class="form-control select2">
                                        @foreach ($topics as $topic)
                                            <option value="{{ $topic->id }}"
                                                    @if($community->topics->contains($topic->id))
                                                        selected
                                                    @endif
                                            >{{ $topic->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            
                            <div class="row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Save') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/communities/index.blade.php
@extends('layouts.app')

@section('content')
        <div class="card">
            <div class="card-header">{{ __('My Community') }}</div>
            
            <div class="card-body">
                @if(session('message'))
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                @endif
                <a href="{{ route('communities.create') }}" class="btn btn-primary">Create
                    Community</a>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($communities as $community)
                        <tr>
                            <td>
                                <a href="{{ route('communities.show', $community) }}">
                                    {{ $community->name }}
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-sm
                                            btn-primary" href="{{ route('communities.edit', $community)
                                             }}"
                                >Edit</a>
                                <form action="{{ route('communities.destroy', $community) }}"
                                      method="POST"
                                      class="d-inline"
                                      onsubmit="return confirm('Are you sure?')">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm
                                            btn-danger">Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="2">
                                No communities yet.
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
@endsection

resources/views/communities/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="float-sm-start">
                {{ $community->name }}
            </div>
            <div class="float-sm-end">
                <a href="{{ route('communities.show', $community) }}"
                
                   @if(request('sort', '') == '')
                       class="btn btn-sm btn-primary mx-1"
                   @else
                       class="btn btn-sm btn-secondary mx-1"
                        @endif>
                    Newest Post
                </a>
                <a href="{{ route('communities.show', $community) }}?sort=popular"
                   style="display: inline;"
                
                   @if(request('sort', '') == 'popular')
                       class="btn btn-sm btn-primary mx-1"
                   @else
                       class="btn btn-sm btn-secondary mx-1"
                        @endif>
                    Popular
                </a>
            </div>
        </div>
        
        <div class="card-body">
            <a href="{{ route('communities.posts.create', $community) }}"
               class="btn btn-sm btn-secondary">
                {{ __('Add Post') }}t</a>
            <hr>
            @forelse($posts as $post)
                <div class="card mb-3">
                    <div class="card-header">
                        {{ $post->title }}
                        <div class="float-sm-end">
                            <p class="" style="display: inline;">
                                {{ $post->created_at->diffForHumans() }}
                            </p>
                        </div>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-1 text-center">
                                
                                @livewire('post-votes', ['post' => $post])
                            
                            </div>
                            <div class="col-11">
                                <p>{!! Str::words($post->post_text, 40) !!}</p>
                            </div>
                        </div>
                    
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <a href="{{ route('communities.posts.show', [$community, $post]) }}"
                                   class="btn btn-sm btn-secondary">
                                    {{ __('View Post') }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
                <p>No posts yet.</p>
            @endforelse
        </div>
        <div class="card-footer">
            
            <div class="row justify-content-center">
                
                
                <div class="col-md-6">
                    
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            {{ $posts->links() }}
                        </div>
                    </div>
                
                </div>
            </div>
        </div>
    </div>
@endsection