routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    App\Http\Controllers\HomeController::class,
    'index'
])->name('home');

Auth::routes([ 'verify' => true ]);

Route::group([
    'middleware' => [
        'auth',
        'verified'
    ]
], function () {

    Route::resource('communities', App\Http\Controllers\CommunityController::class);

    Route::resource('communities.posts', App\Http\Controllers\PostController::class);

    Route::resource('posts.comments', App\Http\Controllers\CommentController::class);

    Route::get('posts/{post_id}/vote/{vote}', [
        App\Http\Controllers\PostVoteController::class,
        'store'
    ])->name('posts.vote');

    Route::post('posts/{post_id}/report', [
        App\Http\Controllers\PostVoteController::class,
        'report'
    ])->name('posts.report');

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    
    <title>{{ config('app.name', 'Laravel') }}</title>
    
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
          rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
          rel="stylesheet"/>
    
    @livewireStyles
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav me-auto">
                
                </ul>
                
                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ms-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif
                        
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#"
                               role="button" data-bs-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>
                            
                            <div class="dropdown-menu dropdown-menu-end"
                                 aria-labelledby="navbarDropdown">
                                
                                <a class="dropdown-item" href="{{ route('communities.index') }}"
                                >
                                    {{ __('My Community') }}
                                </a>
                                
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                
                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>
    
    <main class="py-4">
        
        <div class="container">
            <div class="row ">
                
                <div class="col-6 col-md-4">
                    
                    <div class="card">
                        <div class="card-header">{{ __('News Post') }}</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <ul class="list-group">
                                        @forelse($newestPosts as $post)
                                            <li class="list-group-item">
                                                <a href="{{ route('communities.posts.show',
                                                [$post->community, $post]) }}">
                                                    {{ $post->title }}
                                                </a>
                                            </li>
                                        @empty
                                            <li class="list-group-item">
                                                {{ __('No Post') }}
                                            </li>
                                        @endforelse
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mt-3">
                        <div class="card">
                            <div class="card-header">{{ __('News Community') }}</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <ul class="list-group">
                                            @forelse($newestCommunities as $community)
                                                <li class="list-group-item">
                                                    <a href="{{ route('communities.show', $community) }}">
                                                        {{ $community->name }}
                                                    </a> ({{ $community->posts_count }})
                                                </li>
                                            @empty
                                                <li class="list-group-item">
                                                    {{ __('No Community') }}
                                                </li>
                                            @endforelse
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    @yield('content')
                    
                    @yield('some-content')
                </div>
            
            </div>
        
        </div>
        
        <div class="container-fluid">
            <div class="row justify-content-end">
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </main>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.select2').select2();
    });
</script>

@livewireScripts
</body>
</html>